name: CI Common

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: stable

      - name: Run tests with coverage
        run: |
          go test ./... -covermode=atomic -coverprofile=coverage.out -v

      - name: Upload coverage report
        if: success()
        uses: codecov/codecov-action@v5
        with:
          files: ./coverage.out
          flags: common
          fail_ci_if_error: true
